name: on comment pull request
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '@deploy-storybook'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - if: steps.check.outputs.triggered == 'true'
        uses: actions/checkout@v2
      - if: steps.check.outputs.triggered == 'true'
        name: checkout
        run: |
          git fetch origin +refs/pull/${{ github.event.issue.number }}/merge
          git checkout FETCH_HEAD
      - if: steps.check.outputs.triggered == 'true'
        name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - if: steps.check.outputs.triggered == 'true'
        name: install
        run: yarn install
      - if: steps.check.outputs.triggered == 'true'
        name: storybook
        run: yarn build-storybook
      - if: steps.check.outputs.triggered == 'true'
        name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
      - if: steps.check.outputs.triggered == 'true'
        name: comment
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deployed to https://www.utam0k.jp/vineria-sorcuore'
            })
