name: on comment pull request
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: 'deploy-storybook'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - if: steps.check.outputs.triggered == 'true'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - if: steps.check.outputs.triggered == 'true'
        name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - if: steps.check.outputs.triggered == 'true'
        name: install
        run: yarn install
      - if: steps.check.outputs.triggered == 'true'
        name: storybook
        run: yarn build-storybook
      - if: steps.check.outputs.triggered == 'true'
        name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
      - if: steps.check.outputs.triggered == 'true'
        name: create comments
        run: |
          echo "deploy to https://www.utam0k.jp/vineria-sorcuore" >> comments
          sed -i -z 's/\n/\\n/g' comments
      - if: steps.check.outputs.triggered == 'true'
        name: post comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.comments_url }}
        run: |
          curl -X POST \
              -H "Authorization: token ${GITHUB_TOKEN}" \
              -d "{\"body\": \"$(cat comments)\"}" \
              ${URL}
